<script type="text/javascript" src="../../plugins/jquery/jquery-1.8.3.js"></script>
<script type="text/javascript" src="../../plugins/validate/jquery.validate.js"></script>
<script type="text/javascript" src="../../plugins/jqueryUI/jquery-ui-1.9.2.js"></script>
<script type="text/javascript" src="../../plugins/datatables/jquery.dataTables.js"></script>
<script type="text/javascript" src="../../plugins/datatables/jquery.dataTables.rowGrouping.js"></script>
<script type="text/javascript" src="../../plugins/datatables/TableTools.js"></script>
<script type="text/javascript" src="../../plugins/datatables/ZeroClipboard.js"></script>
<script type="text/javascript" src="../../themes/bootstrap/scripts/bootstrap.js"></script>
<script type="text/javascript" src="../../plugins/scrollto/jquery.scrollTo-1.4.6.js"></script>
<script type="text/javascript" src="../../plugins/jqform/jquery.form-3.31.0.js"></script>
<script type="text/javascript" src="../../plugins/globalize/globalize.js"></script>
<script type="text/javascript" src="../../plugins/menu/krad.navigationMenu.js"></script>
<script type="text/javascript" src="../../plugins/menu/krad.tabMenu.js"></script>
<script type="text/javascript" src="../../themes/kboot/scripts/bootstrap-select.js"></script>
<script type="text/javascript" src="../../themes/kboot/scripts/bootstrap-select-group.js"></script>
<script type="text/javascript" src="../../themes/kboot/scripts/bootstrapSelectPluginOverrides.js"></script>
<script type="text/javascript" src="../../plugins/textpopout/krad.textareaPopout.js"></script>
<script type="text/javascript" src="../../plugins/validate/additional_validations.js"></script>
<script type="text/javascript" src="../../plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="../../plugins/watermark/jquery.watermark.js"></script>
<script type="text/javascript" src="../../plugins/countdown/jquery.countdown.js"></script>
<script type="text/javascript" src="../../plugins/blockUI/jquery.blockUI.js"></script>
<script type="text/javascript" src="../../plugins/color/jquery.color.js"></script>
<script type="text/javascript" src="../../plugins/json/jquery.json-2.2.js"></script>
<script type="text/javascript" src="../../plugins/jqueryUI/jquery.ui.autocomplete.html.js"></script>
<script type="text/javascript" src="../../plugins/easydrag/jquery.easydrag.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.variables.js"></script>

<script type="text/javascript" src="../../krad/scripts/krad.modal.js"></script>


<script type="text/javascript" src="../../krad/scripts/krad.response.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.actions.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.dirty.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.lookup.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.message.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.url.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.validate.js"></script>
<script type="text/javascript" src="../../krad/scripts/krad.widget.js"></script>
<script type="text/javascript" src="../../plugins/easing/jquery.easing-1.3.pack.js"></script>
<script type="text/javascript" src="../../themes/kboot/scripts/less-1.5.0.min.js"></script>
<script type="text/javascript" src="../../themes/kboot/scripts/global.functions.js"></script>